fix: CI macos app notarization

diff --git a/.github/workflows/tags.yml b/.github/workflows/tags.yml
--- a/.github/workflows/tags.yml
+++ b/.github/workflows/tags.yml
@@ -58,6 +58,9 @@ jobs:
           - os: macos-latest
             arch: arm64
     runs-on: ${{ matrix.os }}
+    defaults:
+      run:
+        shell: bash
     environment: production
     permissions:
       contents: write
@@ -96,11 +99,42 @@ jobs:
           ## Decode the Base64 Apple API Key string into the .p8 file
           echo $APPLE_API_KEY_BASE64 | base64 --decode -o $APPLE_API_KEY
       - name: Build electron app
+        run: yarn build-electron
+      - name: Notarize macOS app
+        if: startsWith(matrix.os, 'macos')
         env:
           APPLE_API_KEY: ${{ runner.temp }}/AppleApiKey.p8
           APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
-        run: yarn build-electron
+        run: |
+          cd packages/apps/electron-app/out/make/zip/darwin/${{ matrix.arch }}
+          APP_VERSION="${GITHUB_REF_NAME#v}"
+          APP_ZIP=superego-darwin-${{ matrix.arch }}-$APP_VERSION.zip
+
+          # Submit for notarization and wait for it to finish. The command
+          # output is masked to avoid making the notarization submission id
+          # public.
+          SUBMISSION_OUTPUT=$(xcrun notarytool submit $APP_ZIP --wait --key $APPLE_API_KEY --key-id $APPLE_API_KEY_ID --issuer $APPLE_API_ISSUER)
+          SUBMISSION_ID=$(echo "$SUBMISSION_OUTPUT" | awk '/id: / {print $2}')
+          if [[ -n "$SUBMISSION_ID" ]]; then
+            echo "::add-mask::$SUBMISSION_ID"
+          fi
+          echo "$SUBMISSION_OUTPUT"
+
+          # Staple the app
+          ditto -xk $APP_ZIP .
+          if xcrun stapler staple -v superego.app > /dev/null 2>&1; then
+            echo "Stapling succeeded"
+          else
+            echo "Stapling failed"
+            exit 1
+          fi
+          rm $APP_ZIP
+          ditto -ck --sequesterRsrc --keepParent superego.app $APP_ZIP
+
+          # Print the sha256 of the final zip, to compare it with the release
+          # artifact zip.
+          sha256 $APP_ZIP
       - name: Deploy electron app to GitHub releases
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
